// <auto-generated />
using System;
using Epsic.Authx.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epsic.Authx.Migrations
{
    [DbContext(typeof(CovidDbContext))]
    partial class CovidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Epsic.Authx.Models.TestCovid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTest")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Resultat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeDeTest")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestsCovid");
                });
#pragma warning restore 612, 618
        }
    }
}
